### ISSUE TITLE
 Error about Object.defineProperty

### ISSUE THREAD

**Issue by luomoxu** [warren-bank/Android-WebMonkey#20]
Test on WebMonkey v04.09.00
userscript
```js
// ==UserScript==
// @name         debug
// @namespace    debug
// @version      0.0.2
// @description  debug
// @author       debug
// @match        https://*/*
// @grant        unsafeWindow
// ==/UserScript==
const object1 = {};

Object.defineProperty(object1, 'property1', {
    value: 42,
    writable: false,
});

object1.property1 = 77;


console.log(object1.property1);
```
code from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty

Error info
```
VM346:1189 Uncaught TypeError: Object.defineProperty is not a function
    at Proxy.userscript_wrapper (<anonymous>:1189:8)
    at <anonymous>:1200:22
    at <anonymous>:1201:3
userscript_wrapper @ VM346:1189
（匿名） @ VM346:1200
（匿名） @ VM346:1201

```

**Comment by warren-bank** [comment]
another great catch!
I see what's causing this error.

It's interesting that by adding the `with` wrapper, this error became better exposed.
Previously, this code worked.. because `Object` was referenced from the global scope, rather than being accessed through the proxy.
I haven't tested to confirm, but I would expect that previous releases would behave this same way if calling: `typeof window.Object.defineProperty`

In any case, I'll fix this right now..
thanks again :)

**Comment by warren-bank** [comment]
fixed by [v04.09.01](https://github.com/warren-bank/Android-WebMonkey/releases/tag/v04.09.01).

I know that I keep saying it, but I really do appreciate your extensive testing.
I guess that I'm lazy in that department.. so the help is truly welcome. :)

**Comment by luomoxu** [comment]
another error with this userscript,Test on WebMonkey v04.09.01, Url https://www.google.com/
```js
// ==UserScript==
// @name         debug
// @namespace    debug
// @version      0.0.14
// @description  debug
// @author       debug
// @match        https://*/*
// @require      https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js
// @grant        unsafeWindow
// ==/UserScript==
console.log(document);
```
error info
```
m=bct,cdos,hsm,jsa,qim,rr4R9e,cEt90b,SNUn3,qddgKe,sTsDMc,dtl0hd,eHDfl,YV5bee,d,csi:446 Uncaught TypeError: Illegal invocation
    at Proxy.setTimeout (m=bct,cdos,hsm,jsa,qim,rr4R9e,cEt90b,SNUn3,qddgKe,sTsDMc,dtl0hd,eHDfl,YV5bee,d,csi:446:191)
    at <anonymous>:1188:29240
    at <anonymous>:1188:220
    at Proxy.userscript_wrapper (<anonymous>:1188:225)
    at <anonymous>:1204:22
    at <anonymous>:1205:3
```
Some references that may be useful
https://github.com/JingMatrix/ChromeXt/blob/cc48f048e3fbfc104679b966abd895e6b91610cf/app/src/main/assets/GM.js#L1088
https://github.com/violentmonkey/violentmonkey/blob/afe97f67e37338b1b39d73534a206b24b60951f7/src/injected/web/gm-global-wrapper.js#L107

**Comment by warren-bank** [comment]
I was unable to reproduce..

I tried the following userscripts on 2x very different devices, and both worked properly:

- - - -

userscript 1:
```javascript
// ==UserScript==
// @name         debug
// @namespace    debug
// @version      0.0.1
// @match        *://*/*
// @require      https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js
// @grant        unsafeWindow
// @run-at       document-start
// ==/UserScript==

try {
  console.log(document)
}
catch(e) {
  unsafeWindow.alert(e.message)
}
```

result:
* logged the `document` object to console

- - - -

userscript 2:
```javascript
// ==UserScript==
// @name         debug
// @namespace    debug
// @version      0.0.1
// @match        *://*/*
// @require      https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js
// @grant        unsafeWindow
// @run-at       document-start
// ==/UserScript==

const object1 = {};

Object.defineProperty(object1, 'property1', {
    value: 42,
    writable: false
});

object1.property1 = 77;

unsafeWindow.alert(object1.property1);

window.alert(String(document))

const $body = $('body')
alert($body.length + ': ' + $body.get(0).tagName)
```

result:
* alert: `42`
* alert: `[object HTMLDocument]`
* alert: `1: BODY`

- - - -

notes:
* although both of these work, I should probably say that scripts that access the DOM shouldn't use:
  ```text
    // @run-at document-start
  ```
* instead, they should really be using:
  ```text
    // @run-at document-end
  ```

**Comment by luomoxu** [comment]
This problem does not appear on all websites, I  reproduce only in  https://www.google.com/, with WebVeiw 129 and andorid 9 arm
this script also can reproduce 
```js
// ==UserScript==
// @name         debug
// @namespace    debug
// @version      0.0.1
// @description  debug
// @author       debug
// @match        https://*/*
// @grant        unsafeWindow
// ==/UserScript==
setTimeout(() => {
    console.log("Delayed for 1 second.");
}, "1000");
```
error info
```
m=bct,cdos,hsm,jsa,qim,rr4R9e,cEt90b,SNUn3,qddgKe,sTsDMc,dtl0hd,eHDfl,YV5bee,d,csi:446 Uncaught TypeError: Illegal invocation
    at Proxy.setTimeout (m=bct,cdos,hsm,jsa,qim,rr4R9e,cEt90b,SNUn3,qddgKe,sTsDMc,dtl0hd,eHDfl,YV5bee,d,csi:446:191)
    at Proxy.userscript_wrapper (<anonymous>:1196:1)
    at <anonymous>:1201:22
    at <anonymous>:1202:3
```
I discovered this when I was locating another problem
`document-start` hook with onPageStarted, There are regular occurrences where jquery cannot run properly.

**Comment by warren-bank** [comment]
I'll investigate.. but if it's site-specific, then it's almost certainly an issue with CSP (content security policy),
which is determined by HTTP response headers and is enforced by the browser (ie: WebView).

That being said.. it's usually possible to add a "default" policy that's permissive.
For example, my userscript(s) for Youtube include [the following](https://github.com/warren-bank/crx-Youtube/blob/webmonkey-userscript/es6/webmonkey-userscript/Youtube.user.js#L62-L76):
```javascript
// add support for CSP 'Trusted Type' assignment
const add_default_trusted_type_policy = () => {
  if (typeof unsafeWindow.trustedTypes !== 'undefined') {
    try {
      const passthrough_policy = string => string

      unsafeWindow.trustedTypes.createPolicy('default', {
          createHTML:      passthrough_policy,
          createScript:    passthrough_policy,
          createScriptURL: passthrough_policy
      })
    }
    catch(e) {}
  }
}
```

However, I don't know if I'm comfortable disabling the security policy by default for every webpage that a userscript is added to.
Hmm.. maybe a (non-standard) metadata flag could be used to activate this behavior.

Will report back with findings..

**Comment by warren-bank** [comment]
quick tests in JS console on [google.com](https://www.google.com/)

- - - -

```js
{
  const script = document.createElement('script')
  script.textContent = "setTimeout(() => {console.log('hi')}, 10)"
  document.body.appendChild(script)
}
```
```text
'hi'
```

- - - -

```js
{
  window.location = "javascript:setTimeout(() => {console.log('hi')}, 10);void(0);"
}
```

```text
Refused to run the JavaScript URL because it violates the following Content Security Policy directive:
  "script-src 'nonce-PD7HcyugjCTP-8U-f8iV-A' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:"
Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.
```

**Comment by luomoxu** [comment]
Thanks for clearing up the confusion

**Comment by warren-bank** [comment]
well.. I'm still going to investigate some more.. and kick around ideas for ways to work around CSP issues.

_This_ is where the difference between running in a WebExtension and a WebView really comes into play.
* In a WebExtension, the browser has designed a separate execution environment with elevated privileges that isn't subject to certain security restrictions
* In a WebView, we're working with ordinary javascript that executes in user space.. and is subject to all the same security rules as all other client-side code
  - how restrictive the security rules are is determined by each individual website

**Comment by warren-bank** [comment]
interesting results..

I ran the 2x userscripts listed above on [google.com](https://www.google.com/).. in addition to the 3rd that you suggested:

```javascript
// ==UserScript==
// @name         debug
// @namespace    debug
// @version      0.0.1
// @match        *://*/*
// @grant        unsafeWindow
// @run-at       document-start
// ==/UserScript==

try {
  setTimeout(() => {
    unsafeWindow.alert('Delayed for 1 second')
  }, 1000)
}
catch(e) {
  unsafeWindow.alert(e.message)
}
```

and..

* when: `@run-at document-start`
  - no CSP errors
  - but scripts that need to access the DOM fail to do so
    * for example: the 2nd test userscript that uses the _jQuery_ dependency sees:<br>`$('body').length === 0`
* when: `@run-at document-end`
  - there __are__ CSP errors
    * for example: this 3rd test userscript that simply sets a timer.. logs the error you describe:<br>`Uncaught TypeError: Illegal invocation at Proxy.setTimeout`

**Comment by luomoxu** [comment]
I feel that this is most likely related to the order in which the page runs Javascript.
`@run-at document-start` will run before CSP working most of the time

**Comment by warren-bank** [comment]
darn.. darn.. darn!

ok, good news / bad news.. but mostly good!

good news is: the error caused by calling `setTimeout()` isn't related to CSP.

bad news: this is related to the `get()` method on the Proxy.. and how it returns functions.<br>I though I fixed that, but not fully.. apparently.

case in point..
* this fails:
  ```javascript
    setTimeout(function(){console.log(this)}, 1000)
  ```
* this __works__:
  ```javascript
    setTimeout.bind(unsafeWindow)(function(){console.log(this)}, 1000)
  ```

so ..back to the drawing board with respect to the conditions used for when to call `bind()`.
but at least it's something that I'm allowed to modify, and not a security issue.

**Comment by warren-bank** [comment]
yep..
```javascript
  setTimeout.prototype.constructor === setTimeout
```

..returns `true`,
which is the condition that I added to test for class constructors.
Obviously, `setTimout` isn't a class constructor.. but my code is treating it like one.
And, consequently, _not_ (currently) binding it to the global `unsafeWindow` object.

**Comment by luomoxu** [comment]
congratulations

**Comment by warren-bank** [comment]
something really hinky is going on..

* in my desktop browsers (both Firefox and Chrome), `setTimeout.prototype === undefined`
* why is the code in the WebView saying different?
  - you don't have to answer that :smiley: ..rhetorical question

**Comment by luomoxu** [comment]
My final desired state is that the result on the desktop browsers is the same as in webview, and no additional adjustments are required.
This is a beautiful expectation

**Comment by warren-bank** [comment]
omg.. ok.. I get now!

the issue isn't desktop vs. WebView

the issue is that google.com includes [this javascript file](https://www.google.com/xjs/_/js/k=xjs.hd.en_US.xO1VllNNW5s.es5.O/am=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAABQAAACAAAAAAEAAAAAAAAAAQBBAEAQAAAEAAAAsAAAQDACAAAAAAgAAIACAR5kCgAARAAAAACAAgACAAAAAAQAAgAAAAAAAAIACAAAAAAABAAAAAAAAAAABAgAAAAAAAAAAAAQAAKAHAAAAAAAAAAQEAABDwAAEAAAAAAAA9AFA8AAMKSwAAAAAAAAAAAAAAAAESBDMhQQUBCAAAAAAAAAAAAAAAAAAgEgTFzY/d=1/ed=1/dg=3/br=1/rs=ACT90oGdE_5Bg4tD5PeRD81e1UIquSO3sQ/ee=ALeJib:B8gLwd;AfeaP:TkrAjf;BMxAGc:E5bFse;BgS6mb:fidj5d;BjwMce:cXX2Wb;CxXAWb:YyRLvc;DULqB:RKfG5c;Dkk6ge:JZmW9e;DpcR3d:zL72xf;EABSZ:MXZt9d;ESrPQc:mNTJvc;EVNhjf:pw70Gc;EmZ2Bf:zr1jrb;EnlcNd:WeHg4;F9mqte:UoRcbe;Fmv9Nc:O1Tzwc;G0KhTb:LIaoZ;G6wU6e:hezEbd;GleZL:J1A7Od;HMDDWe:G8QUdb;HoYVKb:PkDN7e;HqeXPd:cmbnH;IBADCc:RYquRb;IoGlCf:b5lhvb;IsdWVc:qzxzOb;JXJSm:ii1RGf;JXS8fb:Qj0suc;JbMT3:M25sS;JsbNhc:Xd8iUd;K5nYTd:ZDZcre;KOxcK:OZqGte;KQzWid:ZMKkN;KcokUb:KiuZBf;KpRAue:Tia57b;LBgRLc:SdcwHb,XVMNvd;LEikZe:byfTOb,lsjVmc;LXA8b:q7OdKd;LsNahb:ucGLNb;Me32dd:MEeYgc;NPKaK:SdcwHb;NSEoX:lazG7b;Np8Qkd:Dpx6qc;Nyt6ic:jn2sGd;OgagBe:cNTe0;OohIYe:mpEAQb;Pjplud:EEDORb,PoEs9b;Q1Ow7b:x5CSu;Q6C5kf:pfdZCe;QGR0gd:Mlhmy;R2kc8b:ALJqWb;R4IIIb:QWfeKf;R9Ulx:CR7Ufe;RCF5Sd:X1kBmd;RDNBlf:zPRCJb;SLtqO:Kh1xYe;SMDL4c:fTfGO,fTfGO;SNUn3:ZwDk9d,x8cHvb;ScI3Yc:e7Hzgb,e7Hzgb;ShpF6e:N0pvGc;SzQQ3e:dNhofb;TxfV6d:YORN0b;U96pRd:FsR04;UBKJZ:LGDJGb;UDrY1c:eps46d;UVmjEd:EesRsb;UVzb9c:IvPZ6d;UyG7Kb:wQd0G;V2HTTe:RolTY;VGRfx:VFqbr;VN6jIc:ddQyuf;VOcgDe:YquhTb;VsAqSb:PGf2Re;VxQ32b:k0XsBb;WCEKNd:I46Hvd;WDGyFe:jcVOxd;Wfmdue:g3MJlb;XUezZ:sa7lqb;YIZmRd:A1yn5d;YV5bee:IvPZ6d;YkQtAf:rx8ur;ZSH6tc:QAvyLe;ZWEUA:afR4Cf;ZlOOMb:P0I0Ec;a56pNe:JEfCwb;aAJE9c:WHW6Ef;aCJ9tf:qKftvc;aZ61od:arTwJ;af0EJf:ghinId;bDXwRe:UsyOtc;bcPXSc:gSZLJb;cEt90b:ws9Tlc;cFTWae:gT8qnd;coJ8e:KvoW8;dIoSBb:ZgGg9b;dLlj2:Qqt3Gf;dowIGb:ebZ3mb,ebZ3mb;dtl0hd:lLQWFe;eBAeSb:Ck63tb;eBZ5Nd:audvde;eHDfl:ofjVkb;eO3lse:nFClrf;euOXY:OZjbQ;g8nkx:U4MzKc;gaub4:TN6bMe;gtVSi:ekUOYd;h3MYod:cEt90b;hK67qb:QWEO5b;heHB1:sFczq;hjRo6e:F62sG;hsLsYc:Vl118;iFQyKf:QIhFr,vfuNJf;imqimf:jKGL2e;jY0zg:Q6tNgc;k2Qxcb:XY51pe;kCQyJ:ueyPK;kMFpHd:OTA3Ae;kbAm9d:MkHyGd;lOO0Vd:OTA3Ae;lbfkyf:MqGdUd;nAFL3:NTMZac,s39S4;nJw4Gd:dPFZH;oGtAuc:sOXFj;oSUNyd:fTfGO,fTfGO;oUlnpc:RagDlc;oVHXxc:HODIOb;okUaUd:wItadb;pKJiXd:VCenhc;pNsl2d:j9Yuyc;pXdRYb:JKoKVe;pj82le:ww04Df;qZx2Fc:j0xrE;qaS3gd:yiLg6e;qafBPd:sgY6Zb;qavrXe:zQzcXe;qddgKe:d7YSfd,x4FYXe;rQSrae:C6D5Fc;ropkZ:UT1DG;sTsDMc:kHVSUb;sZmdvc:rdGEfc;tH4IIe:Ymry6;tosKvd:ZCqP3;trZL0b:qY8PFe;uuQkY:u2V3ud;vEYCNb:FaqsVd;vGrMZ:lPJJ0c;vfVwPd:lcrkwe;w3bZCb:ZPGaIb;w4rSdf:XKiZ9;w9w86d:dt4g2b;wQlYve:aLUfP;wR5FRb:O1Gjze,TtcOte;wV5Pjc:L8KGxe;xBbsrc:NEW1Qc;ysNiMc:CpIBjd;yxTchf:KUM7Z;z97YGf:oug9te;zOsCQe:Ko78Df;zaIgPb:Qtpxbd/m=cdos,hsm,jsa,mb4ZUb,cEt90b,SNUn3,qddgKe,sTsDMc,dtl0hd,eHDfl,YV5bee,d,csi) that redefines `setTimeout` as a class!

if you open any browser to [google.com](https://www.google.com/) and _then_ open the JS console.. you'll see that:
```javascript
    setTimeout.prototype.constructor === setTimeout
```

but.. if you open the JS console on pretty much any other page on the internet.. you'll see that:
```javascript
  setTimeout.prototype === undefined
```

argh!!

**Comment by warren-bank** [comment]
the interesting this is..
and this is probably a test that I should add to my code..
is that calling the class constructor throws an error.

ex:
```javascript
  var x = new setTimeout()
  var y = new setTimeout(function(){}, 1000)
```

both throw:
```text
  Uncaught TypeError: 'setTimeout' called on an object that does not implement interface Window.
```

but again.. this is _only_ for the implementation of `setTimeout` that Google uses.. which is (very) non-standard.

**Comment by luomoxu** [comment]
Javascript is a rigorous and loose world

**Comment by warren-bank** [comment]
and I love it for that..

I'm not a fan of Typescript..
imho, people who want a language that's typed and compiled should be using Golang (or similar)..
but I digress :)

**Comment by luomoxu** [comment]
I'm trying to reference this project as a module
I did a lot of hardcoding to make it work properly in my project before
But every upstream change requires a lot of manual merge operations.
I use git modules and soft link,fix some gradle error
But in the end I felt a stronger and stronger urge to rewrite
I digress too :)
